FROM ubuntu

RUN apt update && apt upgrade -y
   
RUN apt install curl wget unzip python3 -y

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install

RUN curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64 && \
    chmod +x kops && \
    mv kops /usr/local/bin/

RUN cd ~ && \
    wget https://releases.hashicorp.com/terraform/1.3.1/terraform_1.3.1_linux_amd64.zip && \
    unzip terraform_1.3.1_linux_amd64.zip && \
    chmod +x terraform && \
    mv terraform /usr/local/bin && \
    export PATH=$PATH:/usr/local/bin

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256" && \
    echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN apt install inetutils-ping traceroute -y



