# apiVersion: v1
# kind: Service
# metadata:
#   name: grafana
#   namespace: monitoringa1a39175903c54541bad432eb9e6a044-1553615020.us-west-2.elb.amazonaws.com
#   labels:
#     app: grafana
#     component: core
# spec:
#   type: NodePort
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 3000
#     nodePort: 31300
#   selector:
#     app: grafana
#     component: core
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    component: core
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: grafana
    component: core
